[2023-04-23T16:17:09.885+0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: db_train.cr_table manual__2023-04-23T13:17:06.497841+00:00 [queued]>
[2023-04-23T16:17:09.898+0300] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: db_train.cr_table manual__2023-04-23T13:17:06.497841+00:00 [queued]>
[2023-04-23T16:17:09.898+0300] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T16:17:09.898+0300] {taskinstance.py:1289} INFO - Starting attempt 1 of 5
[2023-04-23T16:17:09.898+0300] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T16:17:09.912+0300] {taskinstance.py:1309} INFO - Executing <Task(MySqlOperator): cr_table> on 2023-04-23 13:17:06.497841+00:00
[2023-04-23T16:17:09.917+0300] {standard_task_runner.py:55} INFO - Started process 25414 to run task
[2023-04-23T16:17:09.928+0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'db_train', 'cr_table', 'manual__2023-04-23T13:17:06.497841+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/train_db.py', '--cfg-path', '/tmp/tmpgj7_9_gx']
[2023-04-23T16:17:09.935+0300] {standard_task_runner.py:83} INFO - Job 20: Subtask cr_table
[2023-04-23T16:17:10.119+0300] {task_command.py:389} INFO - Running <TaskInstance: db_train.cr_table manual__2023-04-23T13:17:06.497841+00:00 [running]> on host vladimir-virtual-machine
[2023-04-23T16:17:10.170+0300] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=vladimir
AIRFLOW_CTX_DAG_ID=db_train
AIRFLOW_CTX_TASK_ID=cr_table
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T13:17:06.497841+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T13:17:06.497841+00:00
[2023-04-23T16:17:10.170+0300] {sql.py:262} INFO - Executing: 
            create table if not exists popki (
                dt date primary key,
                dag_id VARCHAR(40) primary key
            )
        
[2023-04-23T16:17:10.183+0300] {base.py:73} INFO - Using connection ID 'mysql_connection_train' for task execution.
[2023-04-23T16:17:10.435+0300] {base.py:73} INFO - Using connection ID 'mysql_connection_train' for task execution.
[2023-04-23T16:17:10.438+0300] {sql.py:375} INFO - Running statement: 
            create table if not exists popki (
                dt date primary key,
                dag_id VARCHAR(40) primary key
            )
        , parameters: None
[2023-04-23T16:17:10.538+0300] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vladimir/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 268, in execute
    output = hook.run(
  File "/home/vladimir/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/vladimir/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/usr/local/lib/python3.10/dist-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.10/dist-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.10/dist-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1068, 'Multiple primary key defined')
[2023-04-23T16:17:10.549+0300] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=db_train, task_id=cr_table, execution_date=20230423T131706, start_date=20230423T131709, end_date=20230423T131710
[2023-04-23T16:17:10.566+0300] {standard_task_runner.py:100} ERROR - Failed to execute job 20 for task cr_table ((1068, 'Multiple primary key defined'); 25414)
[2023-04-23T16:17:10.587+0300] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T16:17:10.605+0300] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
